# Generated by Django 5.0 on 2024-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='project/images'),
        ),
    ]
